service: e-commerce-handler
provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: ap-southeast-2
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/e-commerce
        - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/e-commerce/index/owner_id-state-index
        - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/e-commerce/index/state-index

plugins:
  - serverless-python-requirements

package:
  exclude:
    - Tests/**

functions:
  app:
    handler: main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /